### ISSUE TITLE
Theme update

### ISSUE THREAD

**Issue by VuiMuich** [VentGrey/Epitaph#5]
Greetings fellow adventurer!

You have subimtted a theme to the `leftwm-community-themes`, thank you for this contribution!

Recently we merged a bunch of bigger changes with the release `0.4.0` of `leftwm`.
Some of them are breaking theme compatibility and therefore we would like to request you to update your theme.

The following changes would be required:
- migrate your `theme.toml` to `theme.ron`. You can do this either with `leftwm-theme migrate <path-to/theme.toml>` or by these four simple steps:
    - surround everything with `(...)`
	- replace ` =` with `:`
	- append `,` on each line
	- safe as `theme.ron`
- in your `up` script replace the line `echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe` with `leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"`, or if you arleady use `leftwm-command` replace the file extension.

If possible, it would be nice when you would grant the `leftwm` organisation or some member of the staff and `leftwm-bot` write access to your repo, so we could push little fixes like the command pipe one without bothering your attention.

Again, thank you for contributing to our community themes and have a nice time adventuring in the Unix word.

Bests on behalf of the LeftWM staff,

VuiMuich

**Comment by VentGrey** [comment]
Will do ASAP! :D

**Comment by VuiMuich** [comment]
Btw: how you doing? Have you deleted your discord?

**Comment by VentGrey** [comment]
I did a while ago and made a new account. But around that time I got a job and haven't been able to maintain this theme as much as I'd like to :(

**Comment by VentGrey** [comment]
Fixed in:
- b7a6bd193fc3fadf366cec7e26353deef0970479
- f05a7beb817452307a4753dc51c8f3cceae21889
- ae55c74ba226e755ba0ed14869985bdd35365137

**Comment by VuiMuich** [comment]
:tada: 
Thanks!
